import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Lab Performance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans"
      )}
      suppressHydrationWarning
    >
      <body className="bg-[#D0D9F3]" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}